

version: '2.1'

volumes:
    ros-bin: 
    opencv-lib: 
    opencv-include: 
    usr-lib:

services:
  roscore:
    image: cristidragomir97/roscore
    environment: 
       - UDEV=1
       - ROS_HOSTNAME=roscore
       - ROS_MASTER_URI=http://roscore:11311
    links: 
      - rosboard
      - camera
      - robot-block
    ports:
      - "11311:11311"
    volumes:
      - ros-bin:/opt/ros/noetic
      - opencv-lib:/usr/local/lib/opencv
      - opencv-include:/usr/local/include/opencv
      - usr-lib:/usr/lib/aarch64-linux-gnu


  rosboard:
    image: cristidragomir97/rosboard
    environment: 
       - ROS_HOSTNAME=rosboard
       - ROS_MASTER_URI=http://roscore:11311
    ports:
      - "8888:8888"
    volumes:
      - ros-bin:/opt/ros/noetic




 
  robot-block:
    privileged: true
    build: ./robot
    environment: 
       - UDEV=1
       - ROS_HOSTNAME=robot-block
       - ROS_MASTER_URI=http://roscore:11311
    volumes:
      - ros-bin:/opt/ros/noetic
      - opencv-lib:/usr/local/lib/opencv
      - opencv-include:/usr/local/include/opencv
      - usr-lib:/usr/lib/aarch64-linux-gnu
    ports:
      - "8000:80"
      - "5000:5000"
    devices:
      - "/dev:/dev"

  arduino-block:
    privileged: true
    image: cristidragomir97/arduino-block
    devices:
      - "/dev:/dev"
    environment: 
      - AVRDUDE_CPU=atmega328p 
      - MONITOR_BAUD=115200
      - SERIAL_PORT= /dev/ttyUSB0
      - REPO=github.com/cristidragomir97/motorhead 
      - SKETCH_FOLDER=/usr/sketches
      - ARDUINO_FQBN=arduino:avr:unonano